version: '3'
services:
  postgres:
    image: postgres
    env_file:
        - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - bruno
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mana:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${ENVIRONMENT}
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    networks:
      - bruno
    volumes:
      - strapi-data:/usr/src/app/public/uploads
      - strapi-db-data:/usr/src/app/data

  opsci-strapi-frontend:
    build:
      context: ../opsci-strapi-frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - mana
    env_file:
      - ./.env
    volumes:
      - strapi-db-data:/usr/src/app/data

networks:
  bruno:
    driver: bridge

volumes:
  postgres-data:
  strapi-data:
  strapi-db-data: